/**
 * 技能清单 · 市场与客户（scene: market_customer）
 *
 * 来源：src/config/appRegistry.ts 实测条目 + .env.example 实测绑定
 * 说明：binding_key 指向 providers/bindings.js，不直接写环境变量名（文档 04 §3 禁止）
 */

/** @type {import('../skillTypes.js').SkillManifest[]} */
export const marketCustomerSkills = [
    {
        skill_key: 'market_insight',
        name: '市场洞察',
        scene: 'market_customer',
        summary: '输入行业或品类关键词，输出市场容量、竞争格局与机会点分析。',
        icon: 'Search',
        workflow_version: '1.0',
        execution_mode: 'blocking',
        requires_confirmation: false,
        supported_files: [],
        input_schema: {
            type: 'object',
            properties: {
                query: { type: 'string', title: '洞察主题', description: '行业 / 品类 / 关键词' },
                region: { type: 'string', title: '区域', default: '全国' },
            },
            required: ['query'],
        },
        output_schema: {
            type: 'object',
            properties: {
                summary: { type: 'string', title: '结论摘要' },
                market_size: { type: 'string', title: '市场规模' },
                competitors: { type: 'array', items: { type: 'object' }, title: '竞争格局' },
                opportunities: { type: 'array', items: { type: 'string' }, title: '机会点' },
            },
            required: ['summary'],
        },
        binding_key: 'market_insight',
        artifact_kind: 'json',
        permission: { code: 'skill:market_insight:run', data_scope: 'dept' },
        task: { trackable: true, idempotent: true },
        live: true,
        legacy: { app_id: 'market', routes: ['/api/market-insight'] },
    },
    {
        skill_key: 'marketing_forecast',
        name: '营销预测',
        scene: 'market_customer',
        summary: '基于历史销售与品牌数据，预测月度/季度销售走势。',
        icon: 'BarChart3',
        workflow_version: '1.0',
        execution_mode: 'blocking',
        requires_confirmation: false,
        supported_files: [],
        input_schema: {
            type: 'object',
            properties: {
                period: { type: 'string', enum: ['month', 'quarter'], title: '预测周期', default: 'month' },
                brand: { type: 'string', title: '品牌' },
                months: { type: 'integer', title: '回溯月数', default: 12 },
            },
            required: ['period'],
        },
        output_schema: {
            type: 'object',
            properties: {
                summary: { type: 'string', title: '预测结论' },
                rows: { type: 'array', items: { type: 'object' }, title: '预测明细' },
                confidence: { type: 'number', title: '置信度' },
            },
            required: ['summary', 'rows'],
        },
        binding_key: 'marketing_forecast',
        artifact_kind: 'table',
        permission: { code: 'skill:marketing_forecast:run', data_scope: 'dept' },
        task: { trackable: true, idempotent: false },
        live: true,
        legacy: {
            app_id: 'prediction',
            routes: ['/api/generate-monthly-forecast'],
            note: '绑定 DIFY_CHATFLOW_*（非独立 key），调用前经 maskingUtils 做品牌脱敏',
        },
    },
    {
        skill_key: 'customer_analysis',
        name: '客户分析',
        scene: 'market_customer',
        summary: '输入客户与交易特征，输出客户分层、价值评估与维护建议。',
        icon: 'Users',
        workflow_version: '1.0',
        execution_mode: 'blocking',
        requires_confirmation: false,
        supported_files: [],
        input_schema: {
            type: 'object',
            properties: {
                customer_name: { type: 'string', title: '客户名称' },
                features: { type: 'object', title: '客户特征', description: '交易频次、金额、品类等' },
            },
            required: ['customer_name'],
        },
        output_schema: {
            type: 'object',
            properties: {
                tier: { type: 'string', enum: ['S', 'A', 'B', 'C'], title: '客户分层' },
                summary: { type: 'string', title: '分析结论' },
                suggestions: { type: 'array', items: { type: 'string' }, title: '维护建议' },
            },
            required: ['summary'],
        },
        binding_key: 'customer_analysis',
        artifact_kind: 'json',
        permission: { code: 'skill:customer_analysis:run', data_scope: 'dept' },
        task: { trackable: true, idempotent: true },
        live: true,
        legacy: { app_id: 'customer', routes: ['/api/customer-analysis'] },
    },
    {
        skill_key: 'marketing_analysis',
        name: '营销分析',
        scene: 'market_customer',
        summary: '以对话方式追问营销数据，逐步产出可执行的分析结论。',
        icon: 'TrendingUp',
        workflow_version: '1.0',
        execution_mode: 'chat',
        requires_confirmation: false,
        supported_files: [],
        input_schema: {
            type: 'object',
            properties: {
                message: { type: 'string', title: '提问内容' },
                conversation_id: { type: 'string', title: '会话 ID', description: '多轮对话时回填' },
            },
            required: ['message'],
        },
        output_schema: {
            type: 'object',
            properties: {
                answer: { type: 'string', title: '回答（Markdown）' },
                conversation_id: { type: 'string', title: '会话 ID' },
                references: { type: 'array', items: { type: 'object' }, title: '引用来源' },
            },
            required: ['answer'],
        },
        binding_key: 'marketing_analysis',
        artifact_kind: 'markdown',
        permission: { code: 'skill:marketing_analysis:run', data_scope: 'dept' },
        task: { trackable: true, idempotent: false },
        live: true,
        legacy: { app_id: 'marketing_analysis', routes: ['/api/marketing-analysis'] },
    },
    {
        skill_key: 'review_partner',
        name: '复盘搭子',
        scene: 'market_customer',
        summary: '汇总订单与交易数据，生成经营复盘看板与改进建议。',
        icon: 'BarChart3',
        workflow_version: '1.0',
        execution_mode: 'async',
        requires_confirmation: false,
        supported_files: ['.xlsx', '.xls', '.csv'],
        input_schema: {
            type: 'object',
            properties: {
                period: { type: 'string', title: '复盘周期' },
                file: { type: 'string', format: 'binary', title: '交易数据文件' },
                focus: { type: 'string', title: '关注重点' },
            },
            required: ['period'],
        },
        output_schema: {
            type: 'object',
            properties: {
                summary: { type: 'string', title: '复盘结论' },
                metrics: { type: 'object', title: '关键指标' },
                findings: { type: 'array', items: { type: 'object' }, title: '问题清单' },
                actions: { type: 'array', items: { type: 'string' }, title: '改进行动' },
            },
            required: ['summary'],
        },
        binding_key: 'review_partner',
        artifact_kind: 'dashboard',
        permission: { code: 'skill:review_partner:run', data_scope: 'dept' },
        task: { trackable: true, idempotent: false },
        live: true,
        legacy: {
            app_id: 'review_partner',
            routes: ['/api/review-partner/*'],
            note: '复合技能：绑定 4 个工作流（主流程 + 小程序 + 订单页 + 交易），路由文件 reviewPartnerRoutes.js',
        },
    },
    {
        skill_key: 'sea_marketing',
        name: '出海营销',
        scene: 'market_customer',
        summary: '输入目标国家与品类，输出海外市场进入策略与本地化建议。',
        icon: 'Globe',
        workflow_version: '1.0',
        execution_mode: 'blocking',
        requires_confirmation: false,
        supported_files: [],
        input_schema: {
            type: 'object',
            properties: {
                country: { type: 'string', title: '目标国家/地区' },
                category: { type: 'string', title: '品类' },
                budget: { type: 'string', title: '预算区间' },
            },
            required: ['country', 'category'],
        },
        output_schema: {
            type: 'object',
            properties: {
                summary: { type: 'string', title: '策略摘要' },
                channels: { type: 'array', items: { type: 'object' }, title: '渠道建议' },
                risks: { type: 'array', items: { type: 'string' }, title: '合规风险' },
            },
            required: ['summary'],
        },
        binding_key: 'sea_marketing',
        artifact_kind: 'markdown',
        permission: { code: 'skill:sea_marketing:run', data_scope: 'dept' },
        task: { trackable: true, idempotent: true },
        live: true,
        legacy: { app_id: 'seamarketing', routes: ['/api/sea-marketing'] },
    },
    {
        skill_key: 'key_account',
        name: '大客户档案',
        scene: 'market_customer',
        summary: '维护大客户档案，辅助生成客户画像与拜访策略建议。',
        icon: 'Building2',
        workflow_version: '1.0',
        execution_mode: 'blocking',
        execution_mode_note:
            '迁移期保留同步调用（现有实现即为同步返回）。待任务中心落地后按文档 03 §7 迁移为 async。',
        requires_confirmation: false,
        supported_files: ['.pdf', '.docx'],
        input_schema: {
            type: 'object',
            properties: {
                account_name: { type: 'string', title: '客户名称' },
                file: { type: 'string', format: 'binary', title: '客户资料文件' },
                notes: { type: 'string', title: '补充说明' },
            },
            required: ['account_name'],
        },
        output_schema: {
            type: 'object',
            properties: {
                summary: { type: 'string', title: '客户画像摘要' },
                tags: { type: 'array', items: { type: 'string' }, title: '标签' },
                strategy: { type: 'array', items: { type: 'string' }, title: '维护策略' },
            },
            required: ['summary'],
        },
        binding_key: 'key_account',
        artifact_kind: 'json',
        permission: { code: 'skill:key_account:run', data_scope: 'dept_tree' },
        task: { trackable: true, idempotent: false },
        live: true,
        legacy: { app_id: 'keyaccount', routes: ['/api/key-accounts/*'] },
    },
    {
        skill_key: 'order_suggestion',
        name: '订货建议',
        scene: 'market_customer',
        summary: '基于客户分层/单客户 RFM 特征，输出订货策略与补货建议。',
        icon: 'ShoppingCart',
        workflow_version: '1.0',
        execution_mode: 'blocking',
        requires_confirmation: false,
        supported_files: [],
        input_schema: {
            type: 'object',
            properties: {
                analysis_type: { type: 'string', enum: ['group_strategy', 'single_customer'], title: '分析类型' },
                tier: { type: 'string', title: '客户分层（分组策略必填）' },
                analysis_data: { type: 'string', title: '分析数据 JSON' },
            },
            required: ['analysis_type'],
        },
        output_schema: {
            type: 'object',
            properties: {
                text: { type: 'string', title: '建议文本（Markdown）' },
            },
            required: ['text'],
        },
        binding_key: 'order_suggestion',
        artifact_kind: 'markdown',
        permission: { code: 'skill:order_suggestion:run', data_scope: 'dept' },
        task: { trackable: true, idempotent: true },
        live: true,
        legacy: { app_id: 'customer', routes: ['/api/order-suggestion'] },
    },
];